name: Test Casks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" || true

      - name: Validate cask syntax
        run: |
          for cask in Casks/*.rb; do
            echo "Validating $cask"
            brew cask audit --strict "$cask" || echo "Audit completed with warnings"
          done

      - name: Test cask installation (dry run)
        run: |
          brew tap smartwatermelon/tap .
          # Don't actually install, just test that the cask can be parsed
          brew info --cask progress-indicator
